# Generated by Django 3.1 on 2020-12-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_candidate_cv_file_tsync_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='current_work_place_name',
            new_name='current_work_place',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='cv_file',
            new_name='my_file',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
