# Generated by Django 3.1 on 2020-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201211_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='tsync_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
