# Generated by Django 3.1 on 2020-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20201211_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='tsync_id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
