# Generated by Django 3.1 on 2020-12-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201211_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='my_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
    ]
