# Generated by Django 3.1 on 2020-12-11 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20201211_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='my_file',
            field=models.FileField(null=True, upload_to='', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='tsync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
