# Generated by Django 3.1 on 2020-12-11 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20201211_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='my_file',
            field=models.FileField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
