# Generated by Django 3.1 on 2020-12-11 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201211_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='my_file',
            field=models.FileField(null=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
