# Generated by Django 3.1 on 2020-12-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20201211_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='on_spot_creation_time',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='on_spot_update_time',
        ),
    ]
