# Generated by Django 3.1 on 2020-12-11 16:06

from django.db import migrations
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20201211_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='on_spot_creation_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True, default=912897389),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='on_spot_update_time',
            field=unixtimestampfield.fields.UnixTimeStampField(auto_now=True, default='1231231223'),
            preserve_default=False,
        ),
    ]
