# Generated by Django 3.1 on 2020-12-12 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20201211_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='current_work_place',
            new_name='current_work_place_name',
        ),
    ]
