# Generated by Django 3.1 on 2020-12-14 09:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20201214_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='cv_file_tsync_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
